spring:
  application:
    name: microservice-1

server:
  port: 8081

eureka:
  client:
    serviceUrl:
      defaultZone: http://testuser:pass1234@localhost:8761/eureka/
  instance:
    hostname: localhost
